# Generated by Django 5.2.1 on 2025-07-24 08:04

import merchant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="id",
            field=models.CharField(
                default=merchant.models.generate_id,
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
