# Generated by Django 5.2.1 on 2025-07-24 09:00

import django.db.models.deletion
import merchant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_alter_merchant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Shop Type",
                "verbose_name_plural": "Shop Types",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=merchant.models.generate_shop_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("app_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="merchant.merchant",
                    ),
                ),
                (
                    "shop_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to="merchant.shoptype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
