# Generated by Django 5.2.1 on 2025-07-24 09:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_shoptype_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="email",
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="phone",
            field=models.CharField(max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="merchant.shoptype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="merchant.merchant",
            ),
            preserve_default=False,
        ),
    ]
