# Generated by Django 5.2.1 on 2025-07-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0004_alter_shop_email_alter_shop_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="app_id",
        ),
        migrations.AddField(
            model_name="shoptype",
            name="shop_domain",
            field=models.URLField(default="https://theloft.mw"),
            preserve_default=False,
        ),
    ]
