# Generated by Django 5.2.1 on 2025-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_remove_shop_app_id_shoptype_shop_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shop/"),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="shop-logos/"),
        ),
        migrations.AddField(
            model_name="shoptype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shop-type/"),
        ),
    ]
