# Generated by Django 5.2.1 on 2025-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0006_shop_image_shop_logo_shoptype_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="color_theme",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
