# Generated by Django 5.2.1 on 2025-08-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0007_shop_color_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
    ]
