# Generated by Django 5.2.1 on 2025-08-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0008_shop_deleted_at_shop_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
            },
        ),
    ]
