# Generated by Django 5.2.1 on 2025-07-06 10:51

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MalipoRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200)),
                (
                    "reversal_trans_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_ref",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("failed", "failed"), ("success", "success")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MalipoWithdraw",
            fields=[
                (
                    "withdraw_id",
                    models.CharField(
                        default=payments.models.generate_order_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customerPhone",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "transaction_type_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bankId", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
