# Generated by Django 5.2.1 on 2025-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malipowithdraw",
            name="customerPhone",
            field=models.CharField(default="0998671706", max_length=200),
            preserve_default=False,
        ),
    ]
