# Generated by Django 5.2.1 on 2025-07-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_malipowithdraw_customerphone"),
        ("shop", "0023_booking_booking_cancelled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maliporefund",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop",
                to="shop.shop",
            ),
        ),
    ]
