# Generated by Django 5.2.1 on 2025-07-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0004_alter_shop_email_alter_shop_phone_and_more"),
        ("payments", "0004_alter_maliporefund_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="maliporefund",
            name="order_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="malipowithdraw",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdraws",
                to="merchant.merchant",
            ),
        ),
    ]
