# Generated by Django 5.2.1 on 2025-07-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_maliporefund_order_id_malipowithdraw_merchant"),
        ("shop", "0025_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maliporefund",
            name="order_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="shop.order",
            ),
        ),
    ]
