# Generated by Django 5.2.1 on 2025-07-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
        ("shop", "0018_shop_product_requires_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="approved",
        ),
        migrations.AddField(
            model_name="user",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.shop",
            ),
        ),
    ]
