# Generated by Django 5.2.1 on 2025-07-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0002_remove_user_approved_user_shop"),
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("merchant", "Merchant"),
                    ("seller", "Seller"),
                    ("buyer", "Buyer"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
    ]
