# Generated by Django 5.2.1 on 2025-07-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0003_user_merchant_alter_user_role"),
        ("merchant", "0003_shoptype_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.shop",
            ),
        ),
    ]
