# Generated by Django 5.2.1 on 2025-08-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0004_alter_user_shop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
    ]
