# Generated by Django 5.2.1 on 2025-08-26 13:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchant", "0009_alter_merchant_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyOrderRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchant.shop"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["shop", "date"], name="reporting_d_shop_id_7ac6e3_idx"
                    )
                ],
                "unique_together": {("shop", "date")},
            },
        ),
    ]
