# Generated by Django 5.2.1 on 2025-07-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_sku"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ProductAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredients", models.TextField(blank=True, null=True)),
                (
                    "portion_size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "alcohol_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("preparation_time", models.DurationField(blank=True, null=True)),
                (
                    "is_vegan",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "is_spicy",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="yes",
                        max_length=20,
                    ),
                ),
                ("allergens", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
    ]
