# Generated by Django 5.2.1 on 2025-07-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_category_options_productadditionalinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productadditionalinfo",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_info",
                to="shop.product",
            ),
        ),
    ]
