# Generated by Django 5.2.1 on 2025-07-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_productadditionalinfo_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
            ),
        ),
    ]
