# Generated by Django 5.2.1 on 2025-07-06 02:44

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_productimages_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        default=shop.models.generate_order_id,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("table", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "initiated"),
                            ("pending", "pending"),
                            ("failed", "failed"),
                            ("paid", "paid"),
                            ("delivered", "delivered"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
        ),
    ]
