# Generated by Django 5.2.1 on 2025-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "initiated"),
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                    ("failed", "failed"),
                    ("paid", "paid"),
                    ("delivered", "delivered"),
                ],
                max_length=100,
            ),
        ),
    ]
