# Generated by Django 5.2.1 on 2025-07-08 08:27

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_booking_table_order_booking_booking_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="id",
            field=models.CharField(
                default=shop.models.generate_order_id,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
