# Generated by Django 5.2.1 on 2025-07-16 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_table_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="image",
        ),
        migrations.AddField(
            model_name="order",
            name="custom_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Manual amount for non-product orders",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="table/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
