# Generated by Django 5.2.1 on 2025-07-17 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_booking_duration_minutes_remove_tag_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="order",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="table",
            name="is_active",
        ),
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.order",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="booking_status",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="takeaway",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="booked",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.order",
                    ),
                ),
            ],
        ),
    ]
