# Generated by Django 5.2.1 on 2025-07-17 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_booking_time_slot_remove_order_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="customer_phone",
        ),
        migrations.AddField(
            model_name="booking",
            name="first_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="last_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
