# Generated by Django 5.2.1 on 2025-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_remove_booking_customer_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="time",
            new_name="start_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
