# Generated by Django 5.2.1 on 2025-07-17 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_rename_time_booking_start_time_booking_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="district",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="customer_phone",
        ),
        migrations.AddField(
            model_name="delivery",
            name="first_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="last_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="phone",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "initiated"),
                    ("paid", "paid"),
                    ("delivered", "delivered"),
                ],
                default="initiated",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="table",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.table",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
