# Generated by Django 5.2.1 on 2025-07-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_booking_options_alter_delivery_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="date",
        ),
    ]
