# Generated by Django 5.2.1 on 2025-07-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_remove_delivery_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="table",
        ),
    ]
