# Generated by Django 5.2.1 on 2025-07-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_remove_delivery_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="booked",
        ),
    ]
