# Generated by Django 5.2.1 on 2025-07-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_shop_product_requires_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                default="e1f7e1a6-0e4f-470c-9c24-84f7012676ba",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.shop",
            ),
            preserve_default=False,
        ),
    ]
