# Generated by Django 5.2.1 on 2025-07-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="shop",
            field=models.ForeignKey(
                default="e1f7e1a6-0e4f-470c-9c24-84f7012676ba",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="shop.shop",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="delivery",
            name="shop",
            field=models.ForeignKey(
                default="e1f7e1a6-0e4f-470c-9c24-84f7012676ba",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Delivery",
                to="shop.shop",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                default="e1f7e1a6-0e4f-470c-9c24-84f7012676ba",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="shop.shop",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="shop",
            field=models.ForeignKey(
                default="e1f7e1a6-0e4f-470c-9c24-84f7012676ba",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="shop.shop",
            ),
            preserve_default=False,
        ),
    ]
