# Generated by Django 5.2.1 on 2025-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_booking_shop_delivery_shop_order_shop_table_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_cancelled",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivery_cancelled",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="no", max_length=20
            ),
        ),
    ]
