# Generated by Django 5.2.1 on 2025-07-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0004_alter_user_shop"),
        ("merchant", "0003_shoptype_shop"),
        ("payments", "0004_alter_maliporefund_shop"),
        ("shop", "0023_booking_booking_cancelled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="merchant.shop",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="merchant.shop",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="merchant.shop",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Delivery",
                to="merchant.shop",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="merchant.shop",
            ),
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
