# Generated by Django 5.2.1 on 2025-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_alter_booking_shop_alter_order_shop_alter_table_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "initiated"),
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                    ("failed", "failed"),
                    ("paid", "paid"),
                    ("delivered", "delivered"),
                ],
                default="initiated",
                max_length=100,
            ),
        ),
    ]
