# Generated by Django 5.2.1 on 2025-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RenameField(
            model_name="productadditionalinfo",
            old_name="portion_size",
            new_name="power_rating",
        ),
        migrations.RemoveField(
            model_name="productadditionalinfo",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="productadditionalinfo",
            name="is_spicy",
        ),
        migrations.RemoveField(
            model_name="productadditionalinfo",
            name="is_vegan",
        ),
        migrations.RemoveField(
            model_name="productadditionalinfo",
            name="preparation_time",
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="is_fragile",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no")],
                default="no",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="technical_specs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productadditionalinfo",
            name="warranty_period",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="requires_stock",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")], default="yes", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="productadditionalinfo",
            name="alcohol_percentage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
