# Generated by Django 5.2.1 on 2025-08-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_remove_product_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stock",
            new_name="quantity",
        ),
    ]
