# Generated by Django 5.2.1 on 2025-08-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_rename_stock_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "initiated"),
                    ("paid", "paid"),
                    ("delivered", "delivered"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
